import drip/internal/cli
import drip/internal/error
import drip/internal/project
import gleam/list
import gleam/string
import gleeunit
import helpers
import simplifile

// --- Main --------------------------------------------------------------------

pub fn main() -> Nil {
  gleeunit.main()
}

// --- Init Command ------------------------------------------------------------

pub fn init_scaffolds_stylesheets_test() {
  use directory <- helpers.with_temp_directory("drip_e2e_init")
  write_project(directory)
  write_source_theme(directory, "/* tokens */\n")

  let assert Ok(project) = project.load_from(directory)
  let assert Ok(output) = cli.run(project, ["init"])

  // Theme is fetched from the source verbatim.
  assert simplifile.read(directory <> "/src/ui/theme.css")
    == Ok("/* tokens */\n")

  // Index carries the header and imports the theme.
  assert simplifile.read(directory <> "/src/ui/index.css")
    == Ok(
      "/* Generated by drip; do not edit. Run drip add / drip remove to change it. */\n"
      <> "@import \"./theme.css\";\n",
    )

  // Entry leads with tailwind, then points at the index under the prefix.
  assert simplifile.read(directory <> "/src/app.css")
    == Ok("@import \"tailwindcss\";\n@import \"./ui/index.css\";\n")

  assert string.contains(output, "Initialized drip in src/ui")
  assert_change(output, "created", "src/ui/theme.css")
  assert_change(output, "created", "src/ui/index.css")
  assert_change(output, "created", "src/app.css")
  assert string.contains(output, "gleam run -m drip -- add")
}

pub fn init_does_not_overwrite_existing_index_without_force_test() {
  use directory <- helpers.with_temp_directory("drip_e2e_init_exists")
  write_project(directory)
  write_source_theme(directory, "new\n")
  let assert Ok(Nil) = simplifile.create_directory_all(directory <> "/src/ui")
  let assert Ok(Nil) =
    simplifile.write(to: directory <> "/src/ui/index.css", contents: "old\n")

  let assert Ok(project) = project.load_from(directory)
  let assert Error(error.ProjectFileAlreadyExists(_)) =
    cli.run(project, ["init"])

  // The gate fires before any write, so the pre-existing index is untouched.
  assert simplifile.read(directory <> "/src/ui/index.css") == Ok("old\n")
}

pub fn init_does_not_overwrite_existing_theme_without_force_test() {
  use directory <- helpers.with_temp_directory("drip_e2e_init_theme_exists")
  write_project(directory)
  write_source_theme(directory, "new\n")
  let assert Ok(Nil) = simplifile.create_directory_all(directory <> "/src/ui")
  let assert Ok(Nil) =
    simplifile.write(to: directory <> "/src/ui/theme.css", contents: "old\n")

  let assert Ok(project) = project.load_from(directory)
  let assert Error(error.ProjectFileAlreadyExists(_)) =
    cli.run(project, ["init"])

  // The gate fires before any write, so the pre-existing theme is untouched.
  assert simplifile.read(directory <> "/src/ui/theme.css") == Ok("old\n")
}

pub fn init_force_overwrites_existing_files_test() {
  use directory <- helpers.with_temp_directory("drip_e2e_init_force")
  write_project(directory)
  write_source_theme(directory, "new\n")
  let assert Ok(Nil) = simplifile.create_directory_all(directory <> "/src/ui")
  let assert Ok(Nil) =
    simplifile.write(to: directory <> "/src/ui/theme.css", contents: "old\n")
  let assert Ok(Nil) =
    simplifile.write(to: directory <> "/src/ui/index.css", contents: "stale\n")

  let assert Ok(project) = project.load_from(directory)
  let assert Ok(output) = cli.run(project, ["init", "--force"])

  // Overwriting pre-existing files is reported as modified, not created.
  assert_change(output, "modified", "src/ui/theme.css")
  assert_change(output, "modified", "src/ui/index.css")

  assert simplifile.read(directory <> "/src/ui/theme.css") == Ok("new\n")
  assert simplifile.read(directory <> "/src/ui/index.css")
    == Ok(
      "/* Generated by drip; do not edit. Run drip add / drip remove to change it. */\n"
      <> "@import \"./theme.css\";\n",
    )
}

pub fn init_force_skips_files_whose_content_is_unchanged_test() {
  use directory <- helpers.with_temp_directory("drip_e2e_init_force_noop")
  write_project(directory)
  write_source_theme(directory, "/* tokens */\n")

  // Pre-seed the scaffolded files with exactly what drip would write.
  let assert Ok(Nil) = simplifile.create_directory_all(directory <> "/src/ui")
  let assert Ok(Nil) =
    simplifile.write(
      to: directory <> "/src/ui/theme.css",
      contents: "/* tokens */\n",
    )
  let assert Ok(Nil) =
    simplifile.write(
      to: directory <> "/src/ui/index.css",
      contents: "/* Generated by drip; do not edit. Run drip add / drip remove to change it. */\n"
        <> "@import \"./theme.css\";\n",
    )
  // The entry is already fully wired, so it too is left untouched.
  let assert Ok(Nil) =
    simplifile.write(
      to: directory <> "/src/app.css",
      contents: "@import \"tailwindcss\";\n@import \"./ui/index.css\";\n",
    )

  let assert Ok(project) = project.load_from(directory)
  let assert Ok(output) = cli.run(project, ["init", "--force"])

  // A forced re-init over an already-initialized project changes nothing.
  assert_change(output, "skipped", "src/ui/theme.css")
  assert_change(output, "skipped", "src/ui/index.css")
  assert_change(output, "skipped", "src/app.css")
  assert string.contains(output, "src/ui/theme.css (unchanged)")
  assert string.contains(output, "already initialized")
  assert string.contains(output, "gleam run -m drip -- add")
}

pub fn init_force_re_derives_the_index_from_vendored_elements_test() {
  use directory <- helpers.with_temp_directory("drip_e2e_init_force_vendored")
  write_project(directory)
  write_source_theme(directory, "/* tokens */\n")
  write_registry(
    directory,
    element("button", [], [], ["button.gleam", "button.css"]),
  )
  write_source_file(directory, "button.gleam", "pub const fixture = True\n")
  write_source_file(directory, "button.css", ".button {}\n")

  let assert Ok(project) = project.load_from(directory)
  let assert Ok(_) = cli.run(project, ["init"])
  let assert Ok(_) = cli.run(project, ["add", "button"])

  // Forcing a re-init must rebuild the index from the elements on disk, not
  // reset it to theme-only and orphan button's styles.
  let assert Ok(output) = cli.run(project, ["init", "--force"])

  let assert Ok(index) = simplifile.read(directory <> "/src/ui/index.css")
  assert string.contains(index, "@import \"./theme.css\";")
  assert string.contains(index, "@import \"./button.css\";")

  // The index already imported button, so the re-derived body matches.
  assert_change(output, "unchanged", "src/ui/index.css")
}

pub fn init_leaves_a_fully_wired_entry_unchanged_test() {
  use directory <- helpers.with_temp_directory("drip_e2e_init_entry_wired")
  write_project(directory)
  write_source_theme(directory, "/* tokens */\n")

  // The entry already imports the index.
  let entry = "@import \"tailwindcss\";\n@import \"./ui/index.css\";\n.app {}\n"
  let assert Ok(Nil) = simplifile.create_directory_all(directory <> "/src")
  let assert Ok(Nil) =
    simplifile.write(to: directory <> "/src/app.css", contents: entry)

  let assert Ok(project) = project.load_from(directory)
  let assert Ok(output) = cli.run(project, ["init"])

  assert simplifile.read(directory <> "/src/app.css") == Ok(entry)
  assert_change(output, "unchanged", "src/app.css")
}

pub fn init_appends_index_when_entry_has_tailwind_only_test() {
  use directory <- helpers.with_temp_directory("drip_e2e_init_entry_merge")
  write_project(directory)
  write_source_theme(directory, "/* tokens */\n")

  // A pre-existing entry stylesheet with the consumer's own rules.
  let assert Ok(Nil) = simplifile.create_directory_all(directory <> "/src")
  let assert Ok(Nil) =
    simplifile.write(
      to: directory <> "/src/app.css",
      contents: "@import \"tailwindcss\";\n\n.app {\n  color: red;\n}\n",
    )

  let assert Ok(project) = project.load_from(directory)
  let assert Ok(output) = cli.run(project, ["init"])

  // The index import is spliced in right after the tailwind import
  // and the consumer's own rules are left in place.
  assert simplifile.read(directory <> "/src/app.css")
    == Ok(
      "@import \"tailwindcss\";\n"
      <> "@import \"./ui/index.css\";\n"
      <> "\n.app {\n  color: red;\n}\n",
    )

  assert_change(output, "modified", "src/app.css")
}

pub fn init_prepends_tailwind_and_index_when_existing_entry_lacks_both_test() {
  use directory <- helpers.with_temp_directory("drip_e2e_init_entry_prepend")
  write_project(directory)
  write_source_theme(directory, "/* tokens */\n")

  // A pre-existing entry with no tailwind import.
  let assert Ok(Nil) = simplifile.create_directory_all(directory <> "/src")
  let assert Ok(Nil) =
    simplifile.write(
      to: directory <> "/src/app.css",
      contents: "/* mine */\n.app {}\n",
    )

  let assert Ok(project) = project.load_from(directory)
  let assert Ok(output) = cli.run(project, ["init"])

  // Both imports are prepended, tailwind first, and the consumer's
  // content is kept below them.
  assert simplifile.read(directory <> "/src/app.css")
    == Ok(
      "@import \"tailwindcss\";\n"
      <> "@import \"./ui/index.css\";\n"
      <> "/* mine */\n.app {}\n",
    )

  assert_change(output, "modified", "src/app.css")
}

pub fn init_prepends_tailwind_when_entry_has_index_only_test() {
  use directory <- helpers.with_temp_directory("drip_e2e_init_entry_tw_only")
  write_project(directory)
  write_source_theme(directory, "/* tokens */\n")

  // Entry already imports the index but is missing its tailwind import.
  let assert Ok(Nil) = simplifile.create_directory_all(directory <> "/src")
  let assert Ok(Nil) =
    simplifile.write(
      to: directory <> "/src/app.css",
      contents: "@import \"./ui/index.css\";\n.app {}\n",
    )

  let assert Ok(project) = project.load_from(directory)
  let assert Ok(output) = cli.run(project, ["init"])

  // Tailwind is prepended so it leads; the existing index import stays put.
  assert simplifile.read(directory <> "/src/app.css")
    == Ok(
      "@import \"tailwindcss\";\n" <> "@import \"./ui/index.css\";\n.app {}\n",
    )

  assert_change(output, "modified", "src/app.css")
}

pub fn init_scaffolds_under_a_custom_prefix_test() {
  use directory <- helpers.with_temp_directory("drip_e2e_init_prefix")
  write_project_with_prefix(directory, "lib")
  write_source_theme(directory, "/* tokens */\n")

  let assert Ok(project) = project.load_from(directory)
  let assert Ok(_) = cli.run(project, ["init"])

  // Theme and index land under the prefix; the entry imports the prefixed index.
  assert simplifile.read(directory <> "/src/lib/theme.css")
    == Ok("/* tokens */\n")
  assert simplifile.is_file(directory <> "/src/lib/index.css") == Ok(True)
  assert simplifile.read(directory <> "/src/app.css")
    == Ok("@import \"tailwindcss\";\n@import \"./lib/index.css\";\n")
}

pub fn init_writes_nothing_when_theme_fetch_fails_test() {
  use directory <- helpers.with_temp_directory("drip_e2e_init_fetch_fail")
  write_project(directory)
  // No theme.css at the source: the fetch fails before any file is written.

  let assert Ok(project) = project.load_from(directory)
  let assert Error(error.FailedToReadSourceFile(_, _)) =
    cli.run(project, ["init"])

  assert simplifile.is_file(directory <> "/src/ui/theme.css") == Ok(False)
  assert simplifile.is_file(directory <> "/src/ui/index.css") == Ok(False)
  assert simplifile.is_file(directory <> "/src/app.css") == Ok(False)
}

pub fn init_prefix_flag_records_prefix_and_scaffolds_under_it_test() {
  use directory <- helpers.with_temp_directory("drip_e2e_init_prefix_flag")
  write_project(directory)
  write_source_theme(directory, "/* tokens */\n")

  let assert Ok(project) = project.load_from(directory)
  let assert Ok(output) = cli.run(project, ["init", "--prefix=lib"])

  // The scaffold lands under the requested prefix.
  assert simplifile.read(directory <> "/src/lib/theme.css")
    == Ok("/* tokens */\n")
  assert simplifile.read(directory <> "/src/app.css")
    == Ok("@import \"tailwindcss\";\n@import \"./lib/index.css\";\n")

  // The prefix is recorded under the pre-existing [tools.drip] table, so a fresh
  // load now resolves it.
  let assert Ok(reloaded) = project.load_from(directory)
  assert project.prefix(reloaded) == "lib"

  // gleam.toml shows up as a modified file in the summary.
  assert_change(output, "modified", "gleam.toml")
}

pub fn init_prefix_flag_updates_an_existing_prefix_test() {
  use directory <- helpers.with_temp_directory("drip_e2e_init_prefix_update")
  write_project_with_prefix(directory, "lib")
  write_source_theme(directory, "/* tokens */\n")

  let assert Ok(project) = project.load_from(directory)
  let assert Ok(_) = cli.run(project, ["init", "--prefix=components"])

  // The prefix is rewritten in place; the source key it shares the table with
  // is left intact, so the project still loads under the new prefix.
  let assert Ok(reloaded) = project.load_from(directory)
  assert project.prefix(reloaded) == "components"
  assert simplifile.is_file(directory <> "/src/components/theme.css")
    == Ok(True)
}

pub fn init_prefix_flag_rejects_invalid_prefix_test() {
  use directory <- helpers.with_temp_directory("drip_e2e_init_prefix_invalid")
  write_project(directory)
  write_source_theme(directory, "/* tokens */\n")
  let assert Ok(original) = simplifile.read(directory <> "/gleam.toml")

  let assert Ok(project) = project.load_from(directory)
  let assert Error(error.InvalidPrefix("../evil")) =
    cli.run(project, ["init", "--prefix=../evil"])

  // The invalid prefix is caught before any write; nothing is scaffolded
  // and gleam.toml is unchanged.
  assert simplifile.is_file(directory <> "/src/ui/theme.css") == Ok(False)
  assert simplifile.read(directory <> "/gleam.toml") == Ok(original)
}

pub fn init_source_flag_records_source_and_scaffolds_from_it_test() {
  use directory <- helpers.with_temp_directory("drip_e2e_init_source_flag")
  // A gleam.toml with no source, so the flag is the only thing providing one.
  let assert Ok(Nil) =
    simplifile.write(
      to: directory <> "/gleam.toml",
      contents: "name = \"app\"\n",
    )
  write_source_theme(directory, "/* tokens */\n")

  let assert Ok(project) = project.load_from(directory)
  let assert Ok(output) = cli.run(project, ["init", "--source=" <> directory])

  // The theme is fetched from the flag's source and scaffolded.
  assert simplifile.read(directory <> "/src/ui/theme.css")
    == Ok("/* tokens */\n")

  // The source is recorded in a fresh [tools.drip] table, so a reload resolves
  // it rather than falling back to the default release URL.
  let assert Ok(gleam_toml) = simplifile.read(directory <> "/gleam.toml")
  assert string.contains(gleam_toml, "source = " <> toml_string(directory))
  let assert Ok(_) = project.load_from(directory)

  // gleam.toml shows up as a modified file in the summary.
  assert_change(output, "modified", "gleam.toml")
}

pub fn init_source_flag_rejects_invalid_source_test() {
  use directory <- helpers.with_temp_directory("drip_e2e_init_source_invalid")
  write_project(directory)
  write_source_theme(directory, "/* tokens */\n")
  let assert Ok(original) = simplifile.read(directory <> "/gleam.toml")

  let assert Ok(project) = project.load_from(directory)
  let assert Error(error.InvalidSourceUrl("http://has space")) =
    cli.run(project, ["init", "--source=http://has space"])

  // The invalid source is caught before any write; nothing is scaffolded
  // and gleam.toml is unchanged.
  assert simplifile.is_file(directory <> "/src/ui/theme.css") == Ok(False)
  assert simplifile.read(directory <> "/gleam.toml") == Ok(original)
}

pub fn init_records_prefix_and_source_in_one_edit_test() {
  use directory <- helpers.with_temp_directory("drip_e2e_init_prefix_source")
  let assert Ok(Nil) =
    simplifile.write(
      to: directory <> "/gleam.toml",
      contents: "name = \"app\"\n",
    )
  write_source_theme(directory, "/* tokens */\n")

  let assert Ok(project) = project.load_from(directory)
  let assert Ok(output) =
    cli.run(project, ["init", "--prefix=lib", "--source=" <> directory])

  // Both settings take effect; the theme lands under the new prefix,
  // fetched from the new source.
  assert simplifile.read(directory <> "/src/lib/theme.css")
    == Ok("/* tokens */\n")
  let assert Ok(gleam_toml) = simplifile.read(directory <> "/gleam.toml")
  assert string.contains(gleam_toml, "prefix = \"lib\"")
  assert string.contains(gleam_toml, "source = " <> toml_string(directory))
  let assert Ok(_) = project.load_from(directory)

  // The combined write touches gleam.toml exactly once.
  let modified_gleam_toml =
    output
    |> string.split("\n")
    |> list.filter(fn(line) {
      string.contains(line, "gleam.toml") && string.contains(line, "modified")
    })
  assert list.length(modified_gleam_toml) == 1
}

// --- List Command ------------------------------------------------------------

pub fn list_marks_vendored_entries_test() {
  use directory <- helpers.with_temp_directory("drip_e2e_list_vendored")
  write_project(directory)
  write_registry(
    directory,
    element("button", [], [], []) <> "," <> element("input", [], [], []),
  )
  vendor(directory, "button")

  let assert Ok(project) = project.load_from(directory)
  let assert Ok(output) = cli.run(project, ["list"])

  assert output
    == "2 elements available in the source registry.\n\n"
    <> "  ✓ vendored  button\n"
    <> "    available input\n\n"
    <> "Next steps:\n"
    <> "  gleam run -m drip -- add <element>   vendor an element"
}

pub fn list_reports_empty_registry_test() {
  use directory <- helpers.with_temp_directory("drip_e2e_list_empty")
  write_project(directory)
  write_registry(directory, "")

  let assert Ok(project) = project.load_from(directory)
  let assert Ok(output) = cli.run(project, ["list"])

  assert output == "There are no elements in the source registry."
}

pub fn list_surfaces_missing_registry_test() {
  use directory <- helpers.with_temp_directory("drip_e2e_list_no_registry")
  write_project(directory)

  let assert Ok(project) = project.load_from(directory)
  let assert Error(error.FailedToReadSourceFile(_, _)) =
    cli.run(project, ["list"])
}

pub fn list_rejects_stray_arguments_test() {
  use directory <- helpers.with_temp_directory("drip_e2e_list_stray")
  write_project(directory)

  // list takes no positional args; glint rejects a stray one as a usage error
  // before the command body runs, so the registry is never fetched.
  let assert Ok(project) = project.load_from(directory)
  let assert Error(error.InvalidUsage(_)) = cli.run(project, ["list", "ghost"])
}

// --- Add Command -------------------------------------------------------------

pub fn add_vendors_dependencies_and_wires_index_test() {
  use directory <- helpers.with_temp_directory("drip_e2e_add")
  write_project(directory)
  write_source_theme(directory, "/* tokens */\n")
  write_registry(
    directory,
    element("field", ["separator"], [], ["field.gleam", "field.css"])
      <> ","
      <> element("separator", [], [], ["separator.gleam", "separator.css"]),
  )
  write_source_file(directory, "field.gleam", "import ui/separator\n")
  write_source_file(directory, "field.css", ".field {}\n")
  write_source_file(directory, "separator.gleam", "pub const sep = True\n")
  write_source_file(directory, "separator.css", ".separator {}\n")

  let assert Ok(project) = project.load_from(directory)
  let assert Ok(_) = cli.run(project, ["init"])
  let assert Ok(output) = cli.run(project, ["add", "field"])

  // The requested element and its dependency are both vendored under the prefix.
  assert simplifile.is_file(directory <> "/src/ui/field.gleam") == Ok(True)
  assert simplifile.is_file(directory <> "/src/ui/field.css") == Ok(True)
  assert simplifile.is_file(directory <> "/src/ui/separator.gleam") == Ok(True)
  assert simplifile.is_file(directory <> "/src/ui/separator.css") == Ok(True)

  // The index imports both element stylesheets (sorted) alongside the theme.
  assert simplifile.read(directory <> "/src/ui/index.css")
    == Ok(
      "/* Generated by drip; do not edit. Run drip add / drip remove to change it. */\n"
      <> "@import \"./theme.css\";\n"
      <> "@import \"./field.css\";\n"
      <> "@import \"./separator.css\";\n",
    )

  assert output
    == "Vendored 2 elements into src/ui.\n\n"
    <> "  + created  src/ui/field.gleam\n"
    <> "  + created  src/ui/field.css\n"
    <> "  + created  src/ui/separator.gleam\n"
    <> "  + created  src/ui/separator.css\n"
    <> "  ~ modified src/ui/index.css"
}

pub fn add_rewrites_imports_to_prefix_test() {
  use directory <- helpers.with_temp_directory("drip_e2e_add_prefix")
  write_project_with_prefix(directory, "lib")
  write_source_theme(directory, "")
  write_registry(
    directory,
    element("field", ["separator"], [], ["field.gleam"])
      <> ","
      <> element("separator", [], [], ["separator.gleam"]),
  )
  write_source_file(directory, "field.gleam", "import ui/separator\n")
  write_source_file(directory, "separator.gleam", "pub const sep = True\n")

  let assert Ok(project) = project.load_from(directory)
  let assert Ok(_) = cli.run(project, ["init"])
  let assert Ok(_) = cli.run(project, ["add", "field"])

  // The vendored `ui/` import is rewritten to the configured prefix.
  assert simplifile.read(directory <> "/src/lib/field.gleam")
    == Ok("import lib/separator\n")
}

pub fn add_refuses_before_init_test() {
  use directory <- helpers.with_temp_directory("drip_e2e_add_no_init")
  write_project(directory)

  // No index yet; the precondition fires before any fetch,
  // so the registry is never consulted.
  let assert Ok(project) = project.load_from(directory)
  let assert Error(error.FailedToFindIndexStylesheet(_)) =
    cli.run(project, ["add", "button"])
}

pub fn add_requires_an_element_test() {
  use directory <- helpers.with_temp_directory("drip_e2e_add_empty")
  write_project(directory)

  let assert Ok(project) = project.load_from(directory)
  let assert Error(error.NoElementsRequested("add")) = cli.run(project, ["add"])
}

pub fn add_treats_traversal_name_as_unknown_test() {
  use directory <- helpers.with_temp_directory("drip_e2e_add_traversal")
  write_project(directory)
  write_source_theme(directory, "")
  write_registry(directory, element("button", [], [], ["button.gleam"]))

  // A traversal name simply has no registry entry, so it's an unknown element
  // rather than a special-cased rejection; it never reaches the filesystem.
  let assert Ok(project) = project.load_from(directory)
  let assert Ok(_) = cli.run(project, ["init"])
  let assert Error(error.UnknownElement("../evil")) =
    cli.run(project, ["add", "../evil"])
}

pub fn add_rejects_unknown_element_test() {
  use directory <- helpers.with_temp_directory("drip_e2e_add_unknown")
  write_project(directory)
  write_source_theme(directory, "")
  write_registry(directory, element("button", [], [], ["button.gleam"]))

  let assert Ok(project) = project.load_from(directory)
  let assert Ok(_) = cli.run(project, ["init"])
  let assert Error(error.UnknownElement("ghost")) =
    cli.run(project, ["add", "ghost"])
}

pub fn add_skips_vendored_and_preserves_edits_test() {
  use directory <- helpers.with_temp_directory("drip_e2e_add_skip")
  write_project(directory)
  write_source_theme(directory, "")
  write_registry(
    directory,
    element("button", [], [], ["button.gleam", "button.css"]),
  )
  write_source_file(directory, "button.gleam", "pub const fixture = True\n")
  write_source_file(directory, "button.css", ".button {}\n")

  let assert Ok(project) = project.load_from(directory)
  let assert Ok(_) = cli.run(project, ["init"])
  let assert Ok(_) = cli.run(project, ["add", "button"])

  // A local edit to a vendored, consumer-owned file.
  let assert Ok(Nil) =
    simplifile.write(
      to: directory <> "/src/ui/button.gleam",
      contents: "// mine\n",
    )

  // A plain re-add skips the vendored element, leaving the edit untouched.
  let assert Ok(output) = cli.run(project, ["add", "button"])
  assert simplifile.read(directory <> "/src/ui/button.gleam") == Ok("// mine\n")
  assert output
    == "Requested elements are already vendored in src/ui.\n\n"
    <> "  = skipped button (already vendored)"
}

pub fn add_force_revendors_files_test() {
  use directory <- helpers.with_temp_directory("drip_e2e_add_force")
  write_project(directory)
  write_source_theme(directory, "")
  write_registry(
    directory,
    element("button", [], [], ["button.gleam", "button.css"]),
  )
  write_source_file(directory, "button.gleam", "pub const fixture = True\n")
  write_source_file(directory, "button.css", ".button {}\n")

  let assert Ok(project) = project.load_from(directory)
  let assert Ok(_) = cli.run(project, ["init"])
  let assert Ok(_) = cli.run(project, ["add", "button"])
  let assert Ok(Nil) =
    simplifile.write(
      to: directory <> "/src/ui/button.gleam",
      contents: "// mine\n",
    )

  // --force re-fetches and overwrites, restoring the source content. The
  // stylesheet is re-vendored identically, so it reports as skipped rather
  // than dropping out of the summary.
  let assert Ok(output) = cli.run(project, ["add", "button", "--force"])
  assert simplifile.read(directory <> "/src/ui/button.gleam")
    == Ok("pub const fixture = True\n")
  assert output
    == "Vendored 1 element into src/ui.\n\n"
    <> "  ~ modified src/ui/button.gleam\n"
    <> "  = skipped  src/ui/button.css (unchanged)\n"
    <> "  = skipped  src/ui/index.css (unchanged)"
}

pub fn add_writes_nothing_when_a_fetch_fails_test() {
  use directory <- helpers.with_temp_directory("drip_e2e_add_atomic")
  write_project(directory)
  write_source_theme(directory, "")
  // `broken.gleam` is in the registry but absent at the source, so the fetch
  // fails mid-batch before any write is reached.
  write_registry(
    directory,
    element("broken", [], [], ["broken.css", "broken.gleam"]),
  )
  write_source_file(directory, "broken.css", ".broken {}\n")

  let assert Ok(project) = project.load_from(directory)
  let assert Ok(_) = cli.run(project, ["init"])
  let index_before = simplifile.read(directory <> "/src/ui/index.css")

  let assert Error(error.FailedToReadSourceFile(_, _)) =
    cli.run(project, ["add", "broken"])

  // Nothing is written; not even the file that fetched successfully.
  assert simplifile.is_file(directory <> "/src/ui/broken.css") == Ok(False)
  assert simplifile.is_file(directory <> "/src/ui/broken.gleam") == Ok(False)
  assert simplifile.read(directory <> "/src/ui/index.css") == index_before
}

pub fn add_repairs_a_dropped_index_import_test() {
  use directory <- helpers.with_temp_directory("drip_e2e_add_repair")
  write_project(directory)
  write_source_theme(directory, "")
  write_registry(
    directory,
    element("separator", [], [], ["separator.gleam", "separator.css"]),
  )
  write_source_file(directory, "separator.gleam", "pub const sep = True\n")
  write_source_file(directory, "separator.css", ".separator {}\n")

  let assert Ok(project) = project.load_from(directory)
  let assert Ok(_) = cli.run(project, ["init"])
  let assert Ok(index_fresh) = simplifile.read(directory <> "/src/ui/index.css")
  let assert Ok(_) = cli.run(project, ["add", "separator"])

  // Hand-edit the index to drop separator's import back out.
  let assert Ok(Nil) =
    simplifile.write(
      to: directory <> "/src/ui/index.css",
      contents: index_fresh,
    )

  // Re-adding the already-vendored element regenerates the index from disk.
  let assert Ok(_) = cli.run(project, ["add", "separator"])
  let assert Ok(index) = simplifile.read(directory <> "/src/ui/index.css")
  assert string.contains(index, "@import \"./separator.css\";")
}

pub fn add_reports_ffi_and_packages_test() {
  use directory <- helpers.with_temp_directory("drip_e2e_add_callouts")
  write_project(directory)
  write_source_theme(directory, "")
  write_registry(
    directory,
    element("dropdown_menu", [], ["lustre_portal"], [
      "dropdown_menu.gleam",
      "dropdown_menu.css",
      "dropdown_menu.ffi.mjs",
    ]),
  )
  write_source_file(directory, "dropdown_menu.gleam", "pub const a = True\n")
  write_source_file(directory, "dropdown_menu.css", ".dropdown-menu {}\n")
  write_source_file(
    directory,
    "dropdown_menu.ffi.mjs",
    "export const init = () => {}\n",
  )

  let assert Ok(project) = project.load_from(directory)
  let assert Ok(_) = cli.run(project, ["init"])
  let assert Ok(output) = cli.run(project, ["add", "dropdown_menu"])

  // FFI assets vendor verbatim alongside the module.
  assert simplifile.is_file(directory <> "/src/ui/dropdown_menu.ffi.mjs")
    == Ok(True)

  assert output
    == "Vendored 1 element into src/ui.\n\n"
    <> "  + created  src/ui/dropdown_menu.gleam\n"
    <> "  + created  src/ui/dropdown_menu.css\n"
    <> "  + created  src/ui/dropdown_menu.ffi.mjs\n"
    <> "  ~ modified src/ui/index.css\n\n"
    <> "Next steps:\n"
    <> "  call dropdown_menu.init() from your app start\n"
    <> "  gleam add lustre_portal"
}

// --- Remove Command ----------------------------------------------------------

pub fn remove_deletes_files_and_rewrites_index_test() {
  use directory <- helpers.with_temp_directory("drip_e2e_remove")
  write_project(directory)
  write_source_theme(directory, "/* tokens */\n")
  write_registry(
    directory,
    element("field", ["separator"], [], ["field.gleam", "field.css"])
      <> ","
      <> element("separator", [], [], ["separator.gleam", "separator.css"]),
  )
  write_source_file(directory, "field.gleam", "import ui/separator\n")
  write_source_file(directory, "field.css", ".field {}\n")
  write_source_file(directory, "separator.gleam", "pub const sep = True\n")
  write_source_file(directory, "separator.css", ".separator {}\n")

  let assert Ok(project) = project.load_from(directory)
  let assert Ok(_) = cli.run(project, ["init"])
  let assert Ok(_) = cli.run(project, ["add", "field"])

  let assert Ok(output) = cli.run(project, ["remove", "field"])

  // field's own files are gone...
  assert simplifile.is_file(directory <> "/src/ui/field.gleam") == Ok(False)
  assert simplifile.is_file(directory <> "/src/ui/field.css") == Ok(False)

  // ...but its dependency is left in place.
  assert simplifile.is_file(directory <> "/src/ui/separator.gleam") == Ok(True)
  assert simplifile.is_file(directory <> "/src/ui/separator.css") == Ok(True)

  // The index is re-derived from what's left, dropping field's import.
  assert simplifile.read(directory <> "/src/ui/index.css")
    == Ok(
      "/* Generated by drip; do not edit. Run drip add / drip remove to change it. */\n"
      <> "@import \"./theme.css\";\n"
      <> "@import \"./separator.css\";\n",
    )

  assert output
    == "Removed 1 element from src/ui.\n\n"
    <> "  - deleted  src/ui/field.css\n"
    <> "  - deleted  src/ui/field.gleam\n"
    <> "  ~ modified src/ui/index.css"
}

pub fn remove_deletes_ffi_assets_test() {
  use directory <- helpers.with_temp_directory("drip_e2e_remove_ffi")
  write_project(directory)
  write_source_theme(directory, "")
  write_registry(
    directory,
    element("dropdown_menu", [], [], [
      "dropdown_menu.gleam",
      "dropdown_menu.css",
      "dropdown_menu.ffi.mjs",
    ]),
  )
  write_source_file(directory, "dropdown_menu.gleam", "pub const a = True\n")
  write_source_file(directory, "dropdown_menu.css", ".dropdown-menu {}\n")
  write_source_file(
    directory,
    "dropdown_menu.ffi.mjs",
    "export const init = () => {}\n",
  )

  let assert Ok(project) = project.load_from(directory)
  let assert Ok(_) = cli.run(project, ["init"])
  let assert Ok(_) = cli.run(project, ["add", "dropdown_menu"])

  let assert Ok(_) = cli.run(project, ["remove", "dropdown_menu"])

  // Every vendored asset goes, FFI included.
  assert simplifile.is_file(directory <> "/src/ui/dropdown_menu.gleam")
    == Ok(False)
  assert simplifile.is_file(directory <> "/src/ui/dropdown_menu.css")
    == Ok(False)
  assert simplifile.is_file(directory <> "/src/ui/dropdown_menu.ffi.mjs")
    == Ok(False)

  // With nothing left, the index falls back to just the theme import.
  assert simplifile.read(directory <> "/src/ui/index.css")
    == Ok(
      "/* Generated by drip; do not edit. Run drip add / drip remove to change it. */\n"
      <> "@import \"./theme.css\";\n",
    )
}

pub fn remove_skips_elements_that_are_not_vendored_test() {
  use directory <- helpers.with_temp_directory("drip_e2e_remove_absent")
  write_project(directory)
  write_source_theme(directory, "")

  let assert Ok(project) = project.load_from(directory)
  let assert Ok(_) = cli.run(project, ["init"])

  let assert Ok(output) = cli.run(project, ["remove", "ghost"])

  assert output
    == "No elements to remove from src/ui.\n\n  = skipped ghost (not vendored)"
}

pub fn remove_removes_present_and_skips_absent_test() {
  use directory <- helpers.with_temp_directory("drip_e2e_remove_mixed")
  write_project(directory)
  write_source_theme(directory, "")
  write_registry(
    directory,
    element("button", [], [], ["button.gleam", "button.css"]),
  )
  write_source_file(directory, "button.gleam", "pub const b = True\n")
  write_source_file(directory, "button.css", ".button {}\n")

  let assert Ok(project) = project.load_from(directory)
  let assert Ok(_) = cli.run(project, ["init"])
  let assert Ok(_) = cli.run(project, ["add", "button"])

  let assert Ok(output) = cli.run(project, ["remove", "button", "ghost"])

  assert simplifile.is_file(directory <> "/src/ui/button.gleam") == Ok(False)
  assert output
    == "Removed 1 element from src/ui.\n\n"
    <> "  - deleted  src/ui/button.css\n"
    <> "  - deleted  src/ui/button.gleam\n"
    <> "  ~ modified src/ui/index.css\n\n"
    <> "  = skipped ghost (not vendored)"
}

pub fn remove_only_matches_the_named_element_test() {
  use directory <- helpers.with_temp_directory("drip_e2e_remove_sibling")
  write_project(directory)
  write_source_theme(directory, "")
  write_registry(
    directory,
    element("button", [], [], ["button.gleam", "button.css"])
      <> ","
      <> element("button_group", [], [], [
      "button_group.gleam",
      "button_group.css",
    ]),
  )
  write_source_file(directory, "button.gleam", "pub const b = True\n")
  write_source_file(directory, "button.css", ".button {}\n")
  write_source_file(directory, "button_group.gleam", "pub const bg = True\n")
  write_source_file(directory, "button_group.css", ".button_group {}\n")

  let assert Ok(project) = project.load_from(directory)
  let assert Ok(_) = cli.run(project, ["init"])

  // Two vendored elements whose names share a prefix.
  let assert Ok(_) = cli.run(project, ["add", "button", "button_group"])

  let assert Ok(output) = cli.run(project, ["remove", "button"])

  // Only button's files go; the prefix-sharing sibling is untouched.
  assert simplifile.is_file(directory <> "/src/ui/button.gleam") == Ok(False)
  assert simplifile.is_file(directory <> "/src/ui/button.css") == Ok(False)
  assert simplifile.is_file(directory <> "/src/ui/button_group.gleam")
    == Ok(True)
  assert simplifile.is_file(directory <> "/src/ui/button_group.css") == Ok(True)

  // The index keeps the sibling's stylesheet and drops only button's.
  assert simplifile.read(directory <> "/src/ui/index.css")
    == Ok(
      "/* Generated by drip; do not edit. Run drip add / drip remove to change it. */\n"
      <> "@import \"./theme.css\";\n"
      <> "@import \"./button_group.css\";\n",
    )

  assert output
    == "Removed 1 element from src/ui.\n\n"
    <> "  - deleted  src/ui/button.css\n"
    <> "  - deleted  src/ui/button.gleam\n"
    <> "  ~ modified src/ui/index.css"
}

pub fn remove_refuses_before_init_test() {
  use directory <- helpers.with_temp_directory("drip_e2e_remove_no_init")
  write_project(directory)

  // No index yet; the precondition fires before any file is touched.
  let assert Ok(project) = project.load_from(directory)
  let assert Error(error.FailedToFindIndexStylesheet(_)) =
    cli.run(project, ["remove", "button"])
}

pub fn remove_requires_an_element_test() {
  use directory <- helpers.with_temp_directory("drip_e2e_remove_empty")
  write_project(directory)

  let assert Ok(project) = project.load_from(directory)
  let assert Error(error.NoElementsRequested("remove")) =
    cli.run(project, ["remove"])
}

pub fn remove_treats_traversal_name_as_absent_test() {
  use directory <- helpers.with_temp_directory("drip_e2e_remove_traversal")
  write_project(directory)
  write_source_theme(directory, "")

  let assert Ok(project) = project.load_from(directory)
  let assert Ok(_) = cli.run(project, ["init"])

  // A traversal name matches nothing in the install directory: it's only ever
  // a prefix filter, never a path, so it's safely skipped as not-vendored.
  let assert Ok(output) = cli.run(project, ["remove", "../sketch"])
  assert output
    == "No elements to remove from src/ui.\n\n  = skipped ../sketch (not vendored)"
}

// --- Helpers -----------------------------------------------------------------

// Asserts some output line shows `label  <path>`.
fn assert_change(output: String, label: String, path: String) -> Nil {
  let matches = fn(line) {
    string.contains(line, label) && string.contains(line, path)
  }
  assert output |> string.split("\n") |> list.any(matches)
}

fn toml_string(value: String) -> String {
  let escaped =
    value
    |> string.replace("\\", "\\\\")
    |> string.replace("\"", "\\\"")
  "\"" <> escaped <> "\""
}

// A project whose registry source is the project directory itself.
fn write_project(directory: String) -> Nil {
  let assert Ok(Nil) =
    simplifile.write(
      to: directory <> "/gleam.toml",
      contents: "name = \"app\"\n\n[tools.drip]\nsource = "
        <> toml_string(directory)
        <> "\n",
    )

  Nil
}

fn write_registry(directory: String, elements: String) -> Nil {
  let assert Ok(Nil) =
    simplifile.write(
      to: directory <> "/registry.json",
      contents: "{\"schema_version\":1,\"elements\":[" <> elements <> "]}",
    )

  Nil
}

fn element(
  name: String,
  registry_dependencies: List(String),
  dependencies: List(String),
  files: List(String),
) -> String {
  "{\"name\":\""
  <> name
  <> "\",\"registry_dependencies\":["
  <> json_strings(registry_dependencies)
  <> "],\"dependencies\":["
  <> json_strings(dependencies)
  <> "],\"files\":["
  <> json_strings(files)
  <> "]}"
}

fn json_strings(items: List(String)) -> String {
  items |> list.map(fn(item) { "\"" <> item <> "\"" }) |> string.join(",")
}

fn write_project_with_prefix(directory: String, prefix: String) -> Nil {
  let assert Ok(Nil) =
    simplifile.write(
      to: directory <> "/gleam.toml",
      contents: "name = \"app\"\n\n[tools.drip]\nsource = "
        <> toml_string(directory)
        <> "\nprefix = "
        <> toml_string(prefix)
        <> "\n",
    )

  Nil
}

fn write_source_file(directory: String, name: String, contents: String) -> Nil {
  let assert Ok(Nil) = simplifile.write(to: directory <> "/" <> name, contents:)

  Nil
}

fn vendor(directory: String, name: String) -> Nil {
  let assert Ok(Nil) = simplifile.create_directory_all(directory <> "/src/ui")
  let assert Ok(Nil) =
    simplifile.write(
      to: directory <> "/src/ui/" <> name <> ".gleam",
      contents: "",
    )

  Nil
}

fn write_source_theme(directory: String, contents: String) -> Nil {
  let assert Ok(Nil) =
    simplifile.write(to: directory <> "/theme.css", contents:)

  Nil
}
