import codegen/internal/render
import drip/registry
import gleam/string

// --- Escape ------------------------------------------------------------------

pub fn escape_quote_test() {
  assert render.escape("say \"hi\"") == "say \\\"hi\\\""
}

pub fn escape_backslash_test() {
  assert render.escape("a\\b") == "a\\\\b"
}

pub fn escape_plain_test() {
  assert render.escape("<span>x</span>") == "<span>x</span>"
}

// --- Const Declarations ------------------------------------------------------

pub fn const_declaration_test() {
  assert render.const_declaration("source_html", "<span>x</span>")
    == "pub const source_html: String = \"<span>x</span>\""
}

pub fn const_declaration_escapes_test() {
  assert render.const_declaration("x", "a\"b")
    == "pub const x: String = \"a\\\"b\""
}

// --- Generated Module --------------------------------------------------------

pub fn generated_module_test() {
  assert render.generated_module(["pub const a = 1", "pub const b = 2"])
    == "// Generated by `gleam run` in drip/codegen/. Do not edit by hand.\n\n"
    <> "pub const a = 1\n\npub const b = 2\n"
}

// --- Example Consts ----------------------------------------------------------

pub fn example_const_gleam_name_test() {
  assert string.starts_with(
    render.example_const("preview.gleam", "let x = 1"),
    "pub const preview_html: String = \"",
  )
}

pub fn example_const_css_name_test() {
  assert string.starts_with(
    render.example_const("theme.css", "body {\n}"),
    "pub const theme_css_html: String = \"",
  )
}

// --- Installation Tabs -------------------------------------------------------

pub fn installation_tabs_tuples_no_ffi_test() {
  let element =
    registry.Element(
      name: registry.Button,
      description: "Triggers an action.",
      category: registry.Actions,
      ffi: False,
      registry_dependencies: [],
      dependencies: [],
    )
  assert render.installation_tabs_tuples(element)
    == "    \"button\" -> [#(\"button.gleam\", button.source_html), "
    <> "#(\"button.css\", button.css_html)]"
}

pub fn installation_tabs_tuples_ffi_test() {
  let element =
    registry.Element(
      name: registry.Table,
      description: "A data table.",
      category: registry.DataDisplay,
      ffi: True,
      registry_dependencies: [],
      dependencies: [],
    )
  assert render.installation_tabs_tuples(element)
    == "    \"table\" -> [#(\"table.gleam\", table.source_html), "
    <> "#(\"table.css\", table.css_html), #(\"table.ffi.mjs\", table.ffi_html)]"
}

// --- Basename ----------------------------------------------------------------

pub fn basename_test() {
  assert render.basename("src/ui/button.gleam") == "button.gleam"
}

// --- Element Files -----------------------------------------------------------

pub fn element_files_filters_and_sorts_test() {
  assert render.element_files("button", [
      "badge.css",
      "button.gleam",
      "button.css",
    ])
    == ["button.css", "button.gleam"]
}

// The trailing dot keeps `button` from also claiming `button_group`'s files.
pub fn element_files_excludes_prefix_sibling_test() {
  assert render.element_files("button", [
      "button.gleam", "button_group.gleam", "button.css", "button_group.css",
    ])
    == ["button.css", "button.gleam"]
}

// --- Dependency Closure ------------------------------------------------------

pub fn ensure_dependency_closed_ok_test() {
  let button =
    registry.Element(
      name: registry.Button,
      description: "",
      category: registry.Actions,
      ffi: False,
      registry_dependencies: [],
      dependencies: [],
    )
  let table =
    registry.Element(
      name: registry.Table,
      description: "",
      category: registry.DataDisplay,
      ffi: False,
      registry_dependencies: [registry.Button],
      dependencies: [],
    )
  assert render.ensure_dependency_closed([button, table]) == Ok(Nil)
}

pub fn ensure_dependency_closed_unclosed_test() {
  let table =
    registry.Element(
      name: registry.Table,
      description: "",
      category: registry.DataDisplay,
      ffi: False,
      registry_dependencies: [registry.Button],
      dependencies: [],
    )
  let assert Error(message) = render.ensure_dependency_closed([table])
  assert string.contains(message, "table")
  assert string.contains(message, "button")
}
